version: '3'
services:
  app:
    container_name: docker-node-mongo
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - ./:/usr/src/app
      # - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    restart: always
    ports:
      - '443:3000'
    links: 
      - mongo
  mongo:
     container_name: mongo
     image: mongo
     ports: 
      - '27017:27017'
  
